name: Build and deploy to Github Pages
on: push
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy to Github Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          # Github access token token used to deploy on gh_pages. You can find it on Github.
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          base_href: PWAOfflineNotStarting
